export const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
export const TMDB_KEY = process.env.NEXT_PUBLIC_TMDB_KEY;
export const IMAGE_PATH = process.env.NEXT_PUBLIC_IMAGE_PATH;
export const IMAGE_START = process.env.NEXT_PUBLIC_IMAGE_START;
export const IMAGE_END = process.env.NEXT_PUBLIC_IMAGE_END;
export const SEARCH_IMG = process.env.NEXT_PUBLIC_SEARCH_IMG;
